import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Container } from "react-bootstrap";
import Footer from "../components/Footer";
import NavBar from "../components/Navbar";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>My Boo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/1.png" />
      </Head>
      <NavBar />
      <h1>Ini Pages</h1>
      <Footer />
    </Container>
  );
}
